/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/courses": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
          url?: parameters["rowFilter.courses.url"];
          paid?: parameters["rowFilter.courses.paid"];
          price?: parameters["rowFilter.courses.price"];
          purchased_on?: parameters["rowFilter.courses.purchased_on"];
          completed?: parameters["rowFilter.courses.completed"];
          description?: parameters["rowFilter.courses.description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["courses"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** courses */
          courses?: definitions["courses"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
          url?: parameters["rowFilter.courses.url"];
          paid?: parameters["rowFilter.courses.paid"];
          price?: parameters["rowFilter.courses.price"];
          purchased_on?: parameters["rowFilter.courses.purchased_on"];
          completed?: parameters["rowFilter.courses.completed"];
          description?: parameters["rowFilter.courses.description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.courses.id"];
          created_at?: parameters["rowFilter.courses.created_at"];
          updated_at?: parameters["rowFilter.courses.updated_at"];
          url?: parameters["rowFilter.courses.url"];
          paid?: parameters["rowFilter.courses.paid"];
          price?: parameters["rowFilter.courses.price"];
          purchased_on?: parameters["rowFilter.courses.purchased_on"];
          completed?: parameters["rowFilter.courses.completed"];
          description?: parameters["rowFilter.courses.description"];
        };
        body: {
          /** courses */
          courses?: definitions["courses"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  courses: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
    /** Format: text */
    url?: string;
    /** Format: boolean */
    paid?: boolean;
    /** Format: integer */
    price?: number;
    /** Format: timestamp with time zone */
    purchased_on?: string;
    /** Format: boolean */
    completed?: boolean;
    /** Format: text */
    description?: string;
  };
}

export interface parameters {
  /** @description Preference */
  preferParams: "params=single-object";
  /** @description Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** @description Preference */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description courses */
  "body.courses": definitions["courses"];
  /** Format: bigint */
  "rowFilter.courses.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.courses.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.courses.updated_at": string;
  /** Format: text */
  "rowFilter.courses.url": string;
  /** Format: boolean */
  "rowFilter.courses.paid": string;
  /** Format: integer */
  "rowFilter.courses.price": string;
  /** Format: timestamp with time zone */
  "rowFilter.courses.purchased_on": string;
  /** Format: boolean */
  "rowFilter.courses.completed": string;
  /** Format: text */
  "rowFilter.courses.description": string;
}

export interface operations {}

export interface external {}
